
<?php include '../-local_settings.php';?>
<?php include '../includes/-custom_functions.php';?>
<?php include '../includes/-classes.php';?>
<?php include "../includes/-header.php";?>
<?php include "../includes/-sidebar.php"; ?>
    <h2>Residents and Settlers</h2>
    <div class="col-lg-8">
			<h3>Original residents</h3>
		<p>The Indians considered the waters of Lake Ronkonkoma sacred. Four of the thirteen tribes on Long Island shared its shoreline. These tribes were the Setaukets, the Nissequogues, the Secatogs and the Unkechaugs. Evidence of when the first Indians visited the lake is sketchy, but the activity of the Indians in the Ronkonkoma area is perhaps best evidenced by the vast collection of arrowheads and other stone weapons that have been gathered within the radius of a few miles of the lake. Many of the present legends about the lake derive from these local Indian tribes, The Secatogs, Unkechaugs, Setaukets, and Nissequogues, who utilized the shores of the lake. It is thought that the name Ronkonkoma, which in the Algonquin language means boundary fishing place, was chosen as a logical name by the Indians for this body of water. </p>
			<h3>Early settlers</h3>
		<p>The early settlers of Long Island were mostly people of English descent who had come from Massachusetts in the 1600s. Growth was generally slow in the lake area. They were in no hurry to leave the safety of the Long Island Sound where they had access to boats to carry them away in case of danger. A 1795 survey reported five houses north of the lake and none to the south. In 1834, a Coastal Survey Map gave evidence of fewer than a dozen houses scattered around the lake. In 1655, the Setaukets Tribe was the first to sell its land to the white man. The price was 10 coats, 12 hoes, 12 hatchets, 50 muves (broad awks for drilling wampum), 100 needles, 6 kettles, 10 fathoms of wampum, 7 parcels of powder, a pair of stockings (for a child), 10 pounds of lead, and a dozen knives. The Indians retained the right to hunt, fish, and in some instances, live on the land. It is doubtful that the Indians really understood the meaning of the sale since they had no concept of individual ownership of land as practiced by white men. Before the white man eventually settled in the lake area, however, many Indians had died of small pox and other diseases brought overseas by the settlers. </p>
		<p>Each settler contributed part of the purchase price and received shares in proportion to the amount contributed. These purchases from the Indians were not legally recognized and it was necessary to obtain patents from the king confirming the titles and set boundaries. Patents were granted to William Nicholl (Islip), Richard Bull Smith (Smithtown), Richard Woodhull and several others for Brookhaven. Islip, Smithtown, and Brookhaven formed separate townships with the right to purchase land beginning at the shoreline of Lake Ronkonkoma. This precluded the possibility of ever having a single community with the lake as its natural center. </p>
		<p>The patents were drawn up in England and did not always follow exactly the lines agreed to by the settlers. This led to boundary disputes between the townships in later years. Roughly speaking, the land abutting the rim of Lake Ronkonkoma in the Brookhaven section originally belonged to the Setauket and Unkechaug Tribes, in Smithtown, the Nissequogues, and in Islip, the Secatogs. </p>
		<p>The name Ronkonkoma, which was spelled many different ways, was not used excepting in reference to the lake itself, although in the Smithtown records we find the land around Spectacle Pond called the Ronconkomy Plains and other parcels of land mentioned as being in the vicinity of Ronkonkomy Pond. Records are incomplete since early settlers used family burial plots, but we do know that people lived on the Smithtown side of the lake in the 1740s. </p>
		<p>Regarding early Smithtown history, descendants of the Richard (Bull) Smith family of founding fame, found their way to the shores of lake Ronkonkoma, One Smithtown reference mentions a sale of property in 1734 to Thomas Biggs by Capt. E. Smith, "lying on the north side of Rongconcoma pond not coming within four road of ye said pond" (66 feet). </p>
		<p>Smithtown founder Richard Smith's original holdings included the headwaters of the Nissequogue River east to a ``freshwater pond called Raconkamuck, which translates as "the boundary fishing place" in the Algonquian language. What is now known as Lake Ronkonkoma served as a boundary between lands occupied by four Indian communities: Nissequogues, Setaukets, Secatogues and Unkechaugs. It is now owned by the Town of Islip under the terms of the Nichols Patent, while land around it is controlled by three governments - Smithtown, Islip and Brookhaven. That's because different Indian communities gave separate deeds to the land under their control. </p>	   
    </div>
<?php include "../includes/-footer.php";?>

